### ISSUE TITLE
Proposer un projet de saisie Web

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-raepa-plugin#29]
Pour une saisie Web , il faut simplifier les formulaires ensupprimant certains champs obligatoires qui sont calculés par la base de données comme les champs x et y

**Comment by Gustry** [comment]
C'est fait, non? 
https://github.com/3liz/qgis-raepa-plugin/commit/ab201305b3990ba97785ff7d0b561395a2f20a1e
