### ISSUE TITLE
cannot import name 'postgis' from 'processing.tools' in QGIS 3.14

### ISSUE THREAD

**Issue by envirosolutionspl** [3liz/qgis-raepa-plugin#41]
An error `cannot import name 'postgis' from 'processing.tools'` raises while initializing plugin ver. release 0.3.0

Windows 10
Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS: 3.14.0-Pi Pi, 9f7028fd23 

In QGIS 3.10.7-A Coruña everything works like a charm on the same machine.

**Comment by Gustry** [comment]
Cela doit être corrigé dans la version 0.5.0 https://github.com/3liz/qgis-raepa-plugin/releases/tag/0.5.0

Si vous utilisez le dépôt d'extension QGIS, il doit vous proposer la MAJ.
